Repository AY2223S1-CS2103T-W13-1/tp, pull requests merged in 2022-11, with the labels that each got.

#106 Fix sort such that it sorts [Aa - Zz]
  docs/UserGuide.md
  src/main/java/seedu/studmap/logic/commands/SortCommand.java
  src/main/java/seedu/studmap/model/attribute/Attribute.java
  src/main/java/seedu/studmap/model/attribute/AttributeType.java
Labels: bug

#162 Remove overzealous input validation for StudentID
  src/main/java/seedu/studmap/logic/parser/ParserUtil.java
  src/main/java/seedu/studmap/model/student/StudentID.java
  src/main/java/seedu/studmap/storage/JsonAdaptedStudent.java
Labels: bug

#178 Bug fixes to Sort and updates to Sort UG
  docs/UserGuide.md
  src/main/java/seedu/studmap/logic/commands/SortCommand.java
  src/main/java/seedu/studmap/logic/parser/SortCommandParser.java
  src/main/java/seedu/studmap/model/attribute/Attribute.java
  src/main/java/seedu/studmap/model/student/Email.java
  src/main/java/seedu/studmap/model/student/GitName.java
  src/main/java/seedu/studmap/model/student/Module.java
  src/main/java/seedu/studmap/model/student/Name.java
  src/main/java/seedu/studmap/model/student/Phone.java
  src/main/java/seedu/studmap/model/student/Student.java
  src/main/java/seedu/studmap/model/student/StudentID.java
  src/main/java/seedu/studmap/model/student/TeleHandle.java
  src/main/java/seedu/studmap/model/student/UniqueStudentList.java
Labels: bug, type.UG

#181 Update dr-arrgghh.md
  docs/team/dr-arrgghh.md
Labels: documentation, priority.high

#184 Update draft PPP for highorbit25
  docs/team/highorbit25.md
Labels: documentation

#170 Improve command feedback and remove Student Name input verification
  src/main/java/seedu/studmap/logic/parser/AddCommandParser.java
  src/main/java/seedu/studmap/logic/parser/ParserUtil.java
  src/main/java/seedu/studmap/model/student/Assignment.java
  src/main/java/seedu/studmap/model/student/Attendance.java
  src/main/java/seedu/studmap/model/student/GitName.java
  src/main/java/seedu/studmap/model/student/Name.java
  src/main/java/seedu/studmap/model/student/Participation.java
  src/main/java/seedu/studmap/model/student/Phone.java
  src/main/java/seedu/studmap/model/student/StudentID.java
  src/main/java/seedu/studmap/model/student/TeleHandle.java
  src/test/java/seedu/studmap/logic/commands/CommandTestUtil.java
  src/test/java/seedu/studmap/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/studmap/logic/parser/EditCommandParserTest.java
Labels: bug

#188 Update documentations for UG, DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/FilterCommandSequenceDiagram.puml
  docs/diagrams/MarkCommandSequenceDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/SortCommandSequenceDiagram.puml
  docs/images/BetterModelClassDiagram.png
  docs/images/FilterCommandSequenceDiagram.png
  docs/images/ModelClassDiagram.png
  docs/images/SortCommandSequenceDiagram.png
  docs/images/helpMessage.png
  docs/images/studmap.png
  docs/team/highorbit25.md
Labels: help wanted, type.DG, type.UG, priority.high

#191 Fix assignment crash
  src/main/java/seedu/studmap/model/student/Assignment.java
  src/main/java/seedu/studmap/storage/JsonAdaptedAssignment.java
Labels: bug, priority.high

#197 Update developer guide
  docs/DeveloperGuide.md
Labels: type.DG

#195 Add tests for ImportCsv, fix bug with StudentID being allowed to be empty
  src/main/java/seedu/studmap/logic/imports/ImportCsv.java
  src/main/java/seedu/studmap/logic/parser/ParserUtil.java
  src/main/java/seedu/studmap/model/student/StudentID.java
  src/test/data/ImportCsvTest/headerSize6.csv
  src/test/data/ImportCsvTest/headerSize8.csv
  src/test/data/ImportCsvTest/validFormat.csv
  src/test/data/ImportCsvTest/wrongFormat.csv
  src/test/java/seedu/studmap/logic/imports/ImportCsvTest.java
Labels: bug

#207 Update UG / DG / PPP
  docs/DeveloperGuide.md
  docs/diagrams/MarkActivityDiagram.puml
  docs/diagrams/SortActivityDiagram.puml
  docs/images/diagrams/MarkActivityDiagram.png
  docs/images/diagrams/SortActivityDiagram.png
  docs/team/highorbit25.md
Labels: documentation
