Repository AY2223S1-CS2103T-W13-1/tp, pull requests merged in 2022-10, with the labels that each got.

#33 Feature addtag
  src/main/java/seedu/address/logic/commands/AddTagCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddTagCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/test/java/seedu/address/logic/commands/AddTagCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
Labels: enhancement

#36 Add sort command to sort list by name
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: enhancement

#54 Enhance Sort Command to allow sorting by attributes
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/SortCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/attribute/Attribute.java
  src/main/java/seedu/address/model/attribute/exceptions/AttributeNotFoundException.java
  src/main/java/seedu/address/model/order/Order.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/FilterCommandTest.java
  src/test/java/seedu/address/logic/commands/SortCommandTest.java
Labels: enhancement

#65 Update DG documentation
  docs/DeveloperGuide.md
  docs/diagrams/AddTagActivityDiagram.puml
  docs/diagrams/AddTagSequenceDiagram.puml
  docs/images/AddTagActivityDiagram.png
  docs/images/AddTagSequenceDiagram.png
Labels: documentation, type.DG

#71 Update MarkCommand in DG
  docs/DeveloperGuide.md
  docs/diagrams/MarkCommandClassDiagram.puml
  docs/diagrams/MarkCommandParserClassDiagram.puml
  docs/diagrams/MarkCommandSequenceDiagram.puml
  docs/images/MarkCommandClassDiagram.png
  docs/images/MarkCommandParserClassDiagram.png
  docs/images/MarkCommandSequenceDiagram.png
Labels: documentation, type.DG

#72 Update developer guide for AddTag
  docs/DeveloperGuide.md
Labels: documentation, type.DG

#67 Unify Edit Command
  src/main/java/seedu/studmap/commons/core/Messages.java
  src/main/java/seedu/studmap/commons/core/index/AllIndexGenerator.java
  src/main/java/seedu/studmap/commons/core/index/IndexListGenerator.java
  src/main/java/seedu/studmap/commons/core/index/SingleIndexGenerator.java
  src/main/java/seedu/studmap/logic/commands/AddTagCommand.java
  src/main/java/seedu/studmap/logic/commands/EditCommand.java
  src/main/java/seedu/studmap/logic/commands/EditStudentCommand.java
  src/main/java/seedu/studmap/logic/commands/MarkCommand.java
  src/main/java/seedu/studmap/logic/commands/commons/StudentEditor.java
  src/main/java/seedu/studmap/logic/parser/AddTagCommandParser.java
  src/main/java/seedu/studmap/logic/parser/EditCommandParser.java
  src/main/java/seedu/studmap/logic/parser/EditStudentCommandParser.java
  src/main/java/seedu/studmap/logic/parser/IndexCommandParser.java
  src/main/java/seedu/studmap/logic/parser/MarkCommandParser.java
  src/main/java/seedu/studmap/logic/parser/ParserUtil.java
  src/main/java/seedu/studmap/model/Model.java
  src/main/java/seedu/studmap/model/ModelManager.java
  src/main/java/seedu/studmap/model/student/Attendance.java
  src/main/java/seedu/studmap/model/student/Student.java
  src/test/java/seedu/studmap/logic/commands/AddCommandTest.java
  src/test/java/seedu/studmap/logic/commands/AddTagCommandTest.java
  src/test/java/seedu/studmap/logic/commands/CommandTestUtil.java
  src/test/java/seedu/studmap/logic/commands/EditCommandStudentEditorTest.java
  src/test/java/seedu/studmap/logic/commands/EditCommandTest.java
  src/test/java/seedu/studmap/logic/commands/MarkCommandTest.java
  src/test/java/seedu/studmap/logic/parser/CommandParserTestUtil.java
  src/test/java/seedu/studmap/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/studmap/logic/parser/MarkCommandParserTest.java
  src/test/java/seedu/studmap/logic/parser/StudMapParserTest.java
  src/test/java/seedu/studmap/testutil/EditStudentDescriptorBuilder.java
  src/test/java/seedu/studmap/testutil/StudentUtil.java
Labels: refactor

#70 Update Developer Guide
  docs/DeveloperGuide.md
  docs/diagrams/FilterCommandSequenceDiagram.puml
  docs/images/FilterCommandSequenceDiagram.png
Labels: documentation, type.DG

#76 Draft for Sort Feature DG
  docs/DeveloperGuide.md
Labels: documentation, type.DG

#75 Improve sort
  src/main/java/seedu/studmap/logic/commands/SortCommand.java
  src/main/java/seedu/studmap/logic/parser/ParserUtil.java
  src/main/java/seedu/studmap/logic/parser/SortCommandParser.java
  src/main/java/seedu/studmap/model/Model.java
  src/main/java/seedu/studmap/model/ModelManager.java
  src/main/java/seedu/studmap/model/StudMap.java
  src/main/java/seedu/studmap/model/attribute/Attribute.java
  src/main/java/seedu/studmap/model/attribute/AttributeType.java
  src/main/java/seedu/studmap/model/order/Order.java
  src/main/java/seedu/studmap/model/student/UniqueStudentList.java
  src/test/java/seedu/studmap/logic/commands/AddCommandTest.java
  src/test/java/seedu/studmap/logic/commands/SortCommandTest.java
Labels: enhancement

#84 Add new fields to student
  docs/DeveloperGuide.md
  src/main/java/seedu/studmap/logic/commands/AddCommand.java
  src/main/java/seedu/studmap/logic/commands/EditCommand.java
  src/main/java/seedu/studmap/logic/parser/AddCommandParser.java
  src/main/java/seedu/studmap/logic/parser/CliSyntax.java
  src/main/java/seedu/studmap/logic/parser/EditCommandParser.java
  src/main/java/seedu/studmap/logic/parser/ParserUtil.java
  src/main/java/seedu/studmap/model/attribute/Attribute.java
  src/main/java/seedu/studmap/model/attribute/AttributeType.java
  src/main/java/seedu/studmap/model/student/GitName.java
  src/main/java/seedu/studmap/model/student/Student.java
  src/main/java/seedu/studmap/model/student/StudentData.java
  src/main/java/seedu/studmap/model/student/StudentID.java
  src/main/java/seedu/studmap/model/student/TeleHandle.java
  src/main/java/seedu/studmap/model/util/SampleDataUtil.java
  src/main/java/seedu/studmap/storage/JsonAdaptedStudent.java
  src/main/java/seedu/studmap/ui/StudentCard.java
  src/main/resources/view/StudentListCard.fxml
  src/test/data/JsonSerializableStudMapTest/duplicateStudentStudMap.json
  src/test/data/JsonSerializableStudMapTest/typicalStudentsStudMap.json
  src/test/data/JsonStudMapStorageTest/invalidAndValidStudentStudMap.json
  src/test/java/seedu/studmap/logic/LogicManagerTest.java
  src/test/java/seedu/studmap/logic/commands/CommandTestUtil.java
  src/test/java/seedu/studmap/logic/commands/FilterCommandTest.java
  src/test/java/seedu/studmap/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/studmap/model/student/StudentTest.java
  src/test/java/seedu/studmap/storage/JsonAdaptedStudentTest.java
  src/test/java/seedu/studmap/testutil/EditStudentDescriptorBuilder.java
  src/test/java/seedu/studmap/testutil/StudentBuilder.java
  src/test/java/seedu/studmap/testutil/StudentUtil.java
  src/test/java/seedu/studmap/testutil/TypicalStudents.java
Labels: enhancement, priority.high

#108 Update UG for Sort, Participate, Unparticipate
  docs/UserGuide.md
Labels: documentation, type.UG

#163 Allow more flexible module input
  src/main/java/seedu/studmap/logic/parser/ParserUtil.java
Labels: bug

#105 Update UserGuide for filter
  docs/UserGuide.md
Labels: type.UG
