Repository AY2223S1-CS2103T-W13-1/tp, pull requests merged in 2022-09, with the labels that each got.

#22 Update user guide
  .gitignore
  docs/UserGuide.md
Labels: documentation, type.UG

#25 Update README.md
  README.md
  docs/images/Ui.png
Labels: documentation

#28 Add Use Cases for DG
  docs/DeveloperGuide.md
Labels: documentation, type.DG

#29 Update Index Page
  docs/index.md
Labels: documentation, type.DG
